### ISSUE TITLE
TypeError: Zotero.Styles.get(...).getCiteProc is not a function

### ISSUE THREAD

**Issue by pcavicch** [lifan0127/ai-research-assistant#104]
Hello. Whatever question I ask, the answer is always this:

<pre>{
  "name": "TypeError",
  "message": "Zotero.Styles.get(...).getCiteProc is not a function",
  "stack": "createCitations@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/bootstrap.js -> jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/index.js:52687:15\n_call@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/bootstrap.js -> jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/index.js:67008:46\n"
}</pre>

How can I solve this?
Thanks.

**Comment by lifan0127** [comment]
Hi @pcavicch what is your Zotero version? Could you please check if the following citation style is installed?

http://www.zotero.org/styles/american-chemical-society

**Comment by pcavicch** [comment]
Hi Fan Li,
I solved the problem by first installing the beta version and then
reinstalling the official version.
It seems that the beta version leaves some changes that fixes the problem.

Thank you for your reply.
Best regards
Paolo


Il Lun 29 Lug 2024, 16:04 Fan Li ***@***.***> ha scritto:

**Comment by lifan0127** [comment]
Thanks for the notice. I will close this issue now.
