### ISSUE TITLE
Not getting any answers from the chat #4

### ISSUE THREAD

**Issue by NguyenChinh04** [lifan0127/ai-research-assistant#11]
<img width="939" alt="Screenshot 2023-04-12 at 10 33 31" src="https://user-images.githubusercontent.com/130528611/231343322-b4d9a5d7-5602-4c35-bf14-50364c61ac0c.png">

Hello, thank you for the interesting work. However, I have an issue as the RA did not respond to my question as shown in the picture below. Thanks in advance.

**Comment by wenlzhang** [comment]
I got a similar error and finally got the response "Agent stopped due to max iterations.", which is also mentioned in the following issue: https://github.com/lifan0127/zotero-research-assistant/issues/12

**Comment by lifan0127** [comment]
Hi @NguyenChinh04 I suspect it might be a network issue, as the bot should have no problem with a simple "Hello" question.

Hi @wenlzhang  Regarding "max iterations", as I commented in the other issue (https://github.com/lifan0127/zotero-research-assistant/issues/12#issuecomment-1504806734), it is the expected (but undesirable) behavior for the agent system. I expect it to behave better as we better understand the common pitfalls.

**Comment by NguyenChinh04** [comment]
Thank you for your interest and for answering my question. However I checked my internet, it was working fine, GPT chat still replied me immediately. Not only that, my friend tried fake IP because we are in Vietnam, could this be the cause? However, the Zotero RA still didn't answer me even though I waited an hour. Do you have a solution for our problem?

**Comment by NguyenChinh04** [comment]
@lifan0127 i'm using Macbook air M1, Mac OS Ventura 13.3.1 and Zotero for Mac version 6.0.23. Will these affect the Zotero RA?

**Comment by WttBe** [comment]
I've the same problem as @NguyenChinh04, as stated in the other issue. It might be better to fuse these issues together.

On my side, I'm using Windows 10, with Zotero 6.0.23 as well.

**Comment by lifan0127** [comment]
@NguyenChinh04 @WttBe Sorry for the trouble. Could you please try the latest release? It will display all the intermediate actions which hopefully give us more insight about the issue.

**Comment by linhduongtuan** [comment]
@lifan0127 li
I struggle with the same issue, even I try the latest release (~50 minutes before).
It is so strange.
Linh

**Comment by WttBe** [comment]
> If you don't see any intermediate action or output at all, the bot is probably not doing anything. Just want to confirm again, are you able to access this URL through browser? https://api.openai.com/v1/chat/completions

It opens an error page, stating that I didn't provide an API Key. I tried creating a new API Key, but that doesn't change anything.

> @WttBe I have noticed the same behavior a couple of times but struggled to reproduce it. I'd appreciate if you can share how it happened to you. Thanks!

From what I have been able to see, it might happen when the plugin is updated. Then, I have a window for each version of the plugin.

**Comment by lifan0127** [comment]
> It opens an error page, stating that I didn't provide an API Key. I tried creating a new API Key, but that doesn't change anything.

Thanks! It means you can connect to the OpenAI API. Don't worry about the API key.

> From what I have been able to see, it might happen when the plugin is updated. Then, I have a window for each version of the plugin.

This is very helpful information. I will look into it.

**Comment by jf---** [comment]
> As mentioned in other issues, size of the library might be a part of the problem, as I have 2k+ papers and books in my Zotero library!

Same here, and indeed it would be interesting for the UI to state whether the indexing is complete.
Incredible promising work @lifan0127

**Comment by lifan0127** [comment]
@linhduongtuan and @WttBe  If you ask a "Hello" question but get no response, it has to be some kind of error. Because it doesn't involve any actions or indexes to answer. May I ask you to open Tools > Developer > Error Console and see if there are any error messages?

**Comment by wenlzhang** [comment]
Now I got the desired responses with version 0.0.8! I tested for both "Hello" and more specific questions as before.

**Comment by linhduongtuan** [comment]
@lifan0127 l
here is my error message shown in Error Console. 
![Untitled](https://user-images.githubusercontent.com/22388092/231924009-22198a08-46cb-4f54-827d-4aba128acee6.png)

**Comment by lifan0127** [comment]
Hi @WttBe The duplicate plugin windows should have been fixed in the latest release.

> From what I have been able to see, it might happen when the plugin is updated. Then, I have a window for each version of the plugin.

Hi @linhduongtuan I am still trying to figure out the "not getting any answers" message. Thank you   for sharing the error message.

**Comment by WttBe** [comment]
> Hi @WttBe The duplicate plugin windows should have been fixed in the latest release.

Hi @lifan0127 It seems to be, indeed!

> @linhduongtuan and @WttBe If you ask a "Hello" question but get no response, it has to be some kind of error. Because it doesn't involve any actions or indexes to answer. May I ask you to open Tools > Developer > Error Console and see if there are any error messages?

Here is the message from the error console:
[JavaScript Warning: "Key event not available on some keyboard layouts: key=“i” modifiers=“accel shift alt” id=“key_importFromClipboard”" {file: "chrome://zotero/content/standalone/standalone.xul" line: 0}]

Thanks for the hard work!

**Comment by lifan0127** [comment]
Today I tested the plugin in Win 10 with Zotero 6.0.23, and I was able to get response correctly. I don't have a Macbook to test though.

> Here is the message from the error console: [JavaScript Warning: "Key event not available on some keyboard layouts: key=“i” modifiers=“accel shift alt” id=“key_importFromClipboard”" {file: "chrome://zotero/content/standalone/standalone.xul" line: 0}]

@WttBe Thanks for the info. It seems to be just a warning message originated from Zotero itself (?). It is probably not related.

**Comment by lifan0127** [comment]
Hi everyone, just a heads up that you need to manually remove your Zotera RA plugin and install the new Aria plugin (new name): https://github.com/lifan0127/ai-research-assistant/releases/tag/0.0.11

Why to use a new name? The Zotero project team reached out to me and expressed their concern about possible confusion with the main Zotero product. I respect their opinion and choose to comply.

**Comment by WttBe** [comment]
> @WttBe Thanks for the info. It seems to be just a warning message originated from Zotero itself (?). It is probably not related.

It makes sense. What are the possible next steps to solve this mystery?

**Comment by StoicBearcat** [comment]
Hiya, I have the same issue where Aria gives no response to "Hello" or other queries. I installed the plugin today for the first time (Windows 11). I've provided an API key and can access this URL fine: https://api.openai.com/v1/chat/completions. 
I found a lot of messages in my error console and I'm not sure which are relevant so I've attached screenshots of all of them (sorry for the length). There are error messages that specifically mention Aria in the last screenshot. 
I hope this helps! You're doing awesome work here.
![Screenshot 2023-04-18 1](https://user-images.githubusercontent.com/102498261/232639820-0de40cd6-fc7e-49c2-be87-e2e231a101b4.png)
![Screenshot 2023-04-18 2](https://user-images.githubusercontent.com/102498261/232639824-5b2f5e67-af46-4514-ba57-30fd50817cd4.png)
![Screenshot 2023-04-18 3](https://user-images.githubusercontent.com/102498261/232639827-e691bf85-103a-44e7-866b-bed636173c05.png)
![Screenshot 2023-04-18 4](https://user-images.githubusercontent.com/102498261/232639828-223e5291-2651-4e39-a39c-f690cd380be5.png)

**Comment by lifan0127** [comment]
Hi @StoicBearcat  Thanks. Your error message is similar to @linhduongtuan. What other plugins have you installed? Is it possible to test on another computer?

**Comment by StoicBearcat** [comment]
> Hi @StoicBearcat Thanks. Your error message is similar to @linhduongtuan. What other plugins have you installed? Is it possible to test on another computer?

No problem. The only other Zotero plugins I have currently installed are the LibreOffice and Word integrations. I'll be able to test on another computer when I leave the office in a few hours, so I'll let you know.

**Comment by WttBe** [comment]
> Hi @WttBe Do you see any other error messages? What other plugins have you installed? Is it possible to test on another computer?

Hi @lifan0127 I have several plugins loaded, and a lot of error messages that I thought the be irrelevant for this conversation. But I put them below FYI. I won't be able to test the plugin on another computer though... Hope this helps! Thanks for the work!

![image](https://user-images.githubusercontent.com/115926428/232733967-6c98c1fb-5667-4d50-8bb3-612f9cf1fc3f.png)
![image](https://user-images.githubusercontent.com/115926428/232734519-bfdcf31f-490e-4d8d-babf-bb47f7677ec7.png)
![image](https://user-images.githubusercontent.com/115926428/232734611-b63127f7-5312-4d88-aaf5-d84d1f50b6d8.png)
![image](https://user-images.githubusercontent.com/115926428/232734665-e48dbc0a-b74e-4b5e-bf88-5f54f915897b.png)
![image](https://user-images.githubusercontent.com/115926428/232734706-d2e3cf6c-20ed-491a-b7ab-d87c3e6c84be.png)

**Comment by wenlzhang** [comment]
FYI, I have Zotero 6.0.23-beta.9+9a7486e53 and Aria 0.0.13. Now it works fine.

Therefore, I am wondering if this issue could be related to the version of the tools involved.

**Comment by WttBe** [comment]
I am using the latest versions as well!

**Comment by StoicBearcat** [comment]
I think I've figured out what the problem was in my case; I hadn't realised I'd used up all of my OpenAI free trial tokens (oops), so I switched to the paid plan today. It didn't work straight away after switching, but then I generated a new API key and provided it to Aria, and it worked after restarting Zotero. FYI I also have Zotero version 6.0.23 and Aria 0.0.13.

**Comment by WttBe** [comment]
> I think I've figured out what the problem was in my case; I hadn't realised I'd used up all of my OpenAI free trial tokens (oops), so I switched to the paid plan today. It didn't work straight away after switching, but then I generated a new API key and provided it to Aria, and it worked after restarting Zotero. FYI I also have Zotero version 6.0.23 and Aria 0.0.13.

Oooh! This was indeed the issue for me as well! I did not realise all my tokens expired! Thanks a lot for this good insight! And thanks @lifan0127 for the time you gave us!

**Comment by lifan0127** [comment]
In release 0.0.15, an error handling step has been added during plugin initialization to verify OpenAI connectivity.
