### ISSUE TITLE
High token usage

### ISSUE THREAD

**Issue by h1psta** [lifan0127/ai-research-assistant#110]
I have used only about 5 queries like "Summarize paper X" and "Make a coherent narrative connecting papers X, Y and Z" and it already used 20 cents. 

Other apps that use OpenAI API keys have a much smaller token footprint, is this expected behavior ?

**Comment by h1psta** [comment]
To add to my question, is 4o mini support planned?

**Comment by lifan0127** [comment]
Hi @h1psta, the additional tokens are used to create instruction for LLM to interface with Zotero APIs, in addition to answering questions.

I have just created a new release to support GPT-4o and GPT-4o mini. Please give it a try: https://github.com/lifan0127/ai-research-assistant/releases/tag/0.7.1

Thank you!

**Comment by AIOjPINEDA** [comment]
> Hi @h1psta, the additional tokens are used to create instruction for LLM to interface with Zotero APIs, in addition to answering questions.
> 
> I have just created a new release to support GPT-4o and GPT-4o mini. Please give it a try: https://github.com/lifan0127/ai-research-assistant/releases/tag/0.7.1
> 
> Thank you!

Thanks a lot @lifan0127, I use a very frequently Aria and I was waiting for this update. Your work is highly valued

**Comment by danieltomasz** [comment]
@lifan0127 your latest release in unfortunately not compatible with Zotero 7 (which was released last month) . Thank you for your work!

**Comment by h1psta** [comment]
yeah it would be super nice to enable the  GPT-4o mini in the pre-release Zotero 7 version  :)

**Comment by h1psta** [comment]
@danieltomasz  try my quick-fix https://github.com/lifan0127/ai-research-assistant/issues/124

**Comment by lifan0127** [comment]
Hi @h1psta  Thanks for providing the workaround. I have added a new pre-release for this: 

https://github.com/lifan0127/ai-research-assistant/releases/tag/v0.7.1. 

@danieltomasz  Please manually install this new release.
