### ISSUE TITLE
A quick-fix for using gpt mini model in Zotero 7 :) 

### ISSUE THREAD

**Issue by h1psta** [lifan0127/ai-research-assistant#124]
I just modified the addon/chrome/content/preferences.xhtml to match the version 0.7.1 and pasted it into the source for 0.7.0-z7! 

Seems to be working, but maybe I am missing something as I have no deeper understanding of how Aria works 

[aria.xpi.zip](https://github.com/user-attachments/files/16789161/aria.xpi.zip)

**Comment by lifan0127** [comment]
Hi @h1psta  Thanks for providing the workaround. I have added a new pre-release for this: 

https://github.com/lifan0127/ai-research-assistant/releases/tag/v0.7.1. 

Please manually install this new release.
