### ISSUE TITLE
error: input values have 2 keys

### ISSUE THREAD

**Issue by tiankaima** [lifan0127/ai-research-assistant#132]
Greetings. thanks for the amazing work.

I'm trying to use a OpenAI-compatible api endpoint `api.deepseek.com`. Shows error as the following:

```
<pre>{
  "name": "Error",
  "message": "input values have 2 keys, you must specify an input key or pass only 1 key as input",
  "stack": "sf@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:188:11166\nsaveContext@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:188:12968\ninvoke@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:226:3185\n"
}</pre>
```

Detailed error from error console:

```
Object { action: "error", payload: '{"error":{"name":"TypeError","message":"u.message.additional_kwargs.function_call is undefined","stack":"fg</parseResult/o<@jar:file:///home/tiankaima/.zotero/zotero/u5u0qp7t.default/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:301:534\\nparseResult@jar:file:///home/tiankaima/.zotero/zotero/u5u0qp7t.default/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:301:452\\n"}}' }
```

I've seen similar reports from comments in #85 #62 , where you asked them to file as a new issue. I'd share a deepseek.com API key with you if that helps debugging (they do provide free balance).

I do believe these endpoints are completely OpenAI-compatiable, docs here: <https://platform.deepseek.com/api-docs/api/create-chat-completion/>. thx in advance

**Comment by onehr** [comment]
I've had the same issue, although my proxy was not OpenAI, it should be also OpenAI-compatible.

Thank you in advance for your time and assistance, and I look forward to any guidance you might be able to provide.

**Comment by lifan0127** [comment]
Hi everyone, unfortunately I don't have experience with all the LLMs or a deep understanding of their behaviors. Based on the error message, it appears that the model's output doesn't have the correct format as expected by the bot.
