### ISSUE TITLE
Aria cané see Zotero library

### ISSUE THREAD

**Issue by danielfeloiola** [lifan0127/ai-research-assistant#137]
Hello everyone

Lately I have tried to install Aria (version 0.7.2, on Zotero 7.0.3), however it cannot see my library, and fails to summarise papers.

The error message says "Apologies for the inconvenience. Something has gone wrong within Aria. Please check the error stack for detailed information about the issue." 

And this is the stack:
```
<pre>{
  "name": "TypeError",
  "message": "Zotero.Styles.get(...).getCiteProc is not a function",
  "stack": "tw@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:169:7717\n_call@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:345:1895\n"
}</pre>
```

Looks like an issue with Zotero Styles (but no idea how those two might be related...)

**Comment by lifan0127** [comment]
Hi @danielfeloiola could you please verify if you have the following citation style installed? Thanks!

https://www.zotero.org/styles/american-chemical-society

**Comment by danielfeloiola** [comment]
It worked! Thanks!
