### ISSUE TITLE
RA pop-up blocks zotero screen

### ISSUE THREAD

**Issue by blackimpalagithub** [lifan0127/ai-research-assistant#14]
1) The pop-up that appears when you type Shift-R blocks the zotero window and cannot be moved. This is inconvenient when you want to browse your zotero library for something that has been identified by the RA or if you want to edit a library item with a summary the RA has produced. If you click on the Zotero window to bring it forward, the RA content disappears. You should be able to move or resize the RA window.

2) The text produced by the RA cannot be selected and copied.

**Comment by lifan0127** [comment]
Thanks for your feedback! I agree we need to explore how the chat function can be best integrated with the existing Zotero UI.

We will add the ability to copy chat messages in the next release.

**Comment by luc11** [comment]
We cannot paste the message in the chatbox, can you add this features?

**Comment by lifan0127** [comment]
Hi @luc11 I have no problem pasting text in the chatbox, via ctrl+v or mouse right click. What is your OS?

**Comment by lifan0127** [comment]
The main issue raised by the OP has been addressed. Aria is now displayed in a separate dialog window and will not interfere with the Zotero main window.
