### ISSUE TITLE
Though I followed the instructions I get one error message after the other when trying to make Aria work in Zotero. What exactly do I have to do now?

### ISSUE THREAD

**Issue by tomderreimer** [lifan0127/ai-research-assistant#140]
I have created a fresh API key in my openai-account, copied and pasted it into Aria's form in Zotero and got the following error message:

  "error": {
    "message": "Incorrect API key provided: YOUR_OPE*******_KEY. You can find your API key at https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  },
  "code": "invalid_api_key",
  "param": null,
  "type": "invalid_request_error",
  "attemptNumber": 1,
  "retriesLeft": 6,
  "name": "Error",
  "message": "401 Incorrect API key provided: YOUR_OPE*******_KEY. You can find your API key at https://platform.openai.com/account/api-keys.",
  "stack": "Ae@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:244:3146\nt@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:244:3211\ngu@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:244:4316\ngenerate@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:244:3677\nmakeStatusError@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:247:7509\nmakeRequest@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:247:8402\n"
}</pre>

I then deleted this API key in my openai account, created a new one, copy and pasted it again to the said form and got a new error message, namely:

"error": {
    "type": "invalid_request_error",
    "code": "unknown_url",
    "message": "Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.",
    "param": null
  },
  "code": "unknown_url",
  "param": null,
  "type": "invalid_request_error",
  "attemptNumber": 1,
  "retriesLeft": 6,
  "name": "Error",
  "message": "404 Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.",
  "stack": "Ae@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:244:3146\nt@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:244:3211\nbu@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:244:4460\ngenerate@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:244:3725\nmakeStatusError@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:247:7509\nmakeRequest@jar:file:/<local-profile-dir>/extensions/aria@apex974.com.xpi!/chrome/content/scripts/aria.js:247:8402\n"
}</pre>

I'm no techie an noone using Zotero should need to be one! I never before had so much trouble connecting an app by an API key.
So please let me know, what exactly I need to do to make Aria work seamlessly in Zotero. Thank you very much in advance!

**Comment by lifan0127** [comment]
Hi @tomderreimer, Thanks for reaching out. Please ensure that your API key is exactly the same as copied from OpenAI's website. Also, the OpenAI API Base URL should be the same as shown below:

![image](https://github.com/user-attachments/assets/ba8ea3cf-ae27-4600-bffe-6f8f32042e85)

**Comment by tomderreimer** [comment]
Thank you Fan Li,

I still don’t know why Aria didn’t work “out of the box”. However, I’ve deleted the app in Zotero and then re-installed it: Now it seems to work.

Best

Thomas.

 

Von: Fan Li ***@***.***> 
Gesendet: Sonntag, 27. Oktober 2024 04:24
An: lifan0127/ai-research-assistant ***@***.***>
Cc: tomderreimer ***@***.***>; Mention ***@***.***>
Betreff: Re: [lifan0127/ai-research-assistant] Though I followed the instructions I get one error message after the other when trying to make Aria work in Zotero. What exactly do I have to do now? (Issue #140)

 

Hi @tomderreimer <https://github.com/tomderreimer> , Thanks for reaching out. Please ensure that your API key is exactly the same as copied from OpenAI's website. Also, the OpenAI API Base URL should be the same as shown below:

image.png (view on web) <https://github.com/user-attachments/assets/ba8ea3cf-ae27-4600-bffe-6f8f32042e85>

**Comment by lifan0127** [comment]
Thanks for the update! Please let me know if you run into other issues in the future.
