### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by shhong** [lifan0127/ai-research-assistant#59]
I found that the font size is really small! Are there ways that I can increase the font size? Thanks!

**Comment by lifan0127** [comment]
Hi @shhong  Which operating system (OS) do you use? Could you please provide a screenshot?

**Comment by inspiredearth** [comment]
I agree. Would be great to be able to adjust the font size. I found this issue ticket upon coming here to report this issue myself.

In my case the OS is macOS 14.1. Here is a screenshot.

![CleanShot 2023-11-09 at 11 16 23](https://github.com/lifan0127/ai-research-assistant/assets/667395/85f0c558-e55a-435e-9803-13ddf3c48bd7)

I tried adjusting `extensions.zotero.fontSize` but that has no impact on your extension.

**Comment by lifan0127** [comment]
The zoom feature has been implemented and will be part of the next release. Thanks!

![zoom](https://github.com/lifan0127/ai-research-assistant/assets/7218193/5880d938-6820-4e76-a8fa-edbbbfecf5de)

**Comment by lifan0127** [comment]
Released. Please give it a try and let me know if you have any feedback.

https://github.com/lifan0127/ai-research-assistant/releases/tag/0.6.1

**Comment by inspiredearth** [comment]
@lifan0127 Thanks for this. Seems to be working fine to me. Much appreciated.

**Comment by lifan0127** [comment]
Hi @inspiredearth yes, you can make more granular changes in Preferences > Aria > UI Customization (change the number directly, the up/down arrows don't work)

![image](https://github.com/lifan0127/ai-research-assistant/assets/7218193/541c703a-9d42-4c81-8d31-54b5f3ccea93)
