### ISSUE TITLE
Change the "Shift + R" activation shortcut

### ISSUE THREAD

**Issue by WttBe** [lifan0127/ai-research-assistant#6]
As Shift is also used in combination with letters for writing capital case, it might be worth changing the activation shortcut for a less used combination of keys, or let everyone choose the shortcut (s)he wants to work with.

**Comment by lifan0127** [comment]
Thanks for the suggestion. This seems to be a reasonable addition as we move beyond MVP.

**Comment by WttBe** [comment]
Thanks a lot!

**Comment by 31SFX4** [comment]
Can you also add some other method to activate it, like an entry in the context menu or a button in the toolbar, please?

**Comment by odebroqueville** [comment]
May I kindly suggest adding a setting (text box) in the plugin's preference pane where we can input the keyboard shortcut key combination that we would like to use.

**Comment by inspiredearth** [comment]
I agree with this suggestion. Using SHIFT-R is not recommended as it is a common key combination. 

As the risk of stating the obvious ... SHIFT-[anything] is generally not recommended, as SHIFT is system level modifier (aka. a “shortcut”) for all existing keys (capitalisation of letters, and symbols on number keys, etc.).

**Comment by huachuman** [comment]
Why is it shift? Does the developer realize that any time someone is writing inside the app, for example writing a title or correcting metadata, if they hit Shift+R while writing to create a capital R, it activates the plugin?

I seriously question the sanity of this developer for using this shortcut and not allowing us to change it. In all honesty this is one of the most mentally insane things I've seen a developer do in twenty years of using software.

**Comment by lifan0127** [comment]
It is possible to customize the shortcut key combo now. Please give it a try.

https://github.com/lifan0127/ai-research-assistant/releases/tag/0.6.1

![image](https://github.com/lifan0127/ai-research-assistant/assets/7218193/384f1b03-bcb4-48c0-8167-f8d6eeeb00cb)

**Comment by inspiredearth** [comment]
Thank you @lifan0127, I’ve tested this out, and it appears to work well. Problem resolved, as far as I’m concerned.

I would, however, suggest making something other than SHIFT-R the default. You could, for instance, make the default SHIFT-CONTROL-R, for example. There’s really no point in making it only SHIFT-... as this causes issues of unintended Aria activation for the user.

**Comment by lifan0127** [comment]
@inspiredearth Thank you for your feedback. I agree that "Shift + R" is problematic and was a poor decision on my part. However, for now, I will need to keep it as the default for the sake of backward compatibility, to prevent confusion among existing users.

**Comment by huachuman** [comment]
This dev makes no sense

**Comment by WttBe** [comment]
Thanks for the work, @lifan0127! Clearly, you are taking comments into account :)
