### ISSUE TITLE
Display issue (icon size) in Preferences panel (macOS)

### ISSUE THREAD

**Issue by inspiredearth** [lifan0127/ai-research-assistant#60]
Hi there,
There seems to be a bug in the sizing of the Aria icon in the Zotero Preferences on macOS. As shown here:

![Screenshot 2023-11-03 at 2 46 13 PM](https://github.com/lifan0127/ai-research-assistant/assets/667395/09258c6b-cae8-4be6-abb5-03e237a33316)

This is on Zotero v6.0.29
macOS 13.5.2

**Comment by lifan0127** [comment]
Thanks @inspiredearth ! This issue has been raised previously https://github.com/lifan0127/ai-research-assistant/issues/10#issuecomment-1605703473

I think I have identified the issue now and will push a fix in the next release.

**Comment by lifan0127** [comment]
Hi @inspiredearth , could you please try the latest release and let me know: https://github.com/lifan0127/ai-research-assistant/releases/tag/0.5.1

**Comment by lifan0127** [comment]
Hi @inspiredearth I'd appreciate it if you can confirm if the issue is fixed. Thanks

**Comment by inspiredearth** [comment]
Hello Lifan. Yes, I can confirm this issue is now resolved. 
![image](https://github.com/lifan0127/ai-research-assistant/assets/667395/2b8bba8d-1af5-4e7a-b800-c5fcf18808e1)
