### ISSUE TITLE
Appearance and font size

### ISSUE THREAD

**Issue by mrmakethewatergofresh** [lifan0127/ai-research-assistant#64]
When working on a laptop with high resolution the font size at the moment makes it not readable. Potentially three different font sizes to choose or a webbrowserlike experience where one can zoom in as he wants.

![image](https://github.com/lifan0127/ai-research-assistant/assets/110231925/c1006346-ef38-4c99-a44b-42cff3b975e1)
This it how it looks like

**Comment by lifan0127** [comment]
Hi @mrmakethewatergofresh  Thanks for your feedback. What is your OS?

**Comment by mrmakethewatergofresh** [comment]
Windows 10 22H2

**Comment by lifan0127** [comment]
Could you please include the main Zotero UI as part of your screenshot for comparison?

**Comment by mrmakethewatergofresh** [comment]
![image](https://github.com/lifan0127/ai-research-assistant/assets/110231925/eb7b1939-1b41-4314-8455-5ff98ae0e2bd)
Here you go

**Comment by lifan0127** [comment]
I see some of the texts are smaller than the Zoterol main UI. Let me see what I can do.

Btw, if the responses are not satisfactory, please consider sharing your feedback. It would greatly help the development.

![image](https://github.com/lifan0127/ai-research-assistant/assets/7218193/1ff1f4c1-5b7b-4010-b194-654fffe275cc)

**Comment by mrmakethewatergofresh** [comment]
Ok great, I'll mark the queries that are unsatisfactory and looking forward to a better UI :)

**Comment by lifan0127** [comment]
The zoom feature has been implemented and will be part of the next release. Thanks!

![zoom](https://github.com/lifan0127/ai-research-assistant/assets/7218193/c2bb0d1c-158c-4efb-8462-5d30c6976f49)

**Comment by mrmakethewatergofresh** [comment]
How great is that! That's awesome thanks a lot looking forward to it!

**Comment by lifan0127** [comment]
Released. Please give it a try and let me know if you have any feedback.

https://github.com/lifan0127/ai-research-assistant/releases/tag/0.6.1
