### ISSUE TITLE
Cannot resize window

### ISSUE THREAD

**Issue by artofbeinghuman** [lifan0127/ai-research-assistant#65]
The aria chat window is not re-sizeable on macOS. Can this be changed?

**Comment by artofbeinghuman** [comment]
Hi @lifan0127,

the minimize window function does actually help already, thanks.

This is what it looks like, as you can see the minimize and enlarge buttons in the top left of the window are greyed out and hovering over the edges of the window also doesnt bring up the resizing cursor.

<img width="726" alt="image" src="https://github.com/lifan0127/ai-research-assistant/assets/19737739/846d3e9c-bbb4-49ae-ac2d-f3f91e94d774">

Can I provide you with some other kind of information, in hoping this might be fixable?

Thank you, 
Marvin

**Comment by lifan0127** [comment]
Thanks for the additional info. Let me consult with other plugin developers. I don't have experience with macOS.

**Comment by artofbeinghuman** [comment]
Works like a charm now, thank you very much @lifan0127 !!!!
Have a nice day and thanks again for this great addon.
Marvin :)

**Comment by lifan0127** [comment]
Special thanks to @windingwind for this fix!
